export const about = [
      "👨‍💻 About Me:",
      "=====================================",
      "",
      "I'm a technology-driven builder with 6+ years of diverse industry experience, working across software development, product engineering, and tech leadership.",
      "At my core, I’m an explorer—constantly pushing beyond surface-level knowledge to understand how systems work, how products scale, and how innovation happens.",
      "Currently, I’m leading as the CEO of one venture, and serving as Co-Founder & CTO for three others, where I focus on merging cutting-edge technologies with real-world problem solving.",
      "I don’t believe in staying confined to one stack, toolset, or methodology. Versatility is essential in a world that changes fast, and I embrace it fully.",
      "My daily routine involves deep research, hands-on prototyping, and working closely with teams to turn complex challenges into executable solutions.",
      "From cloud infrastructure to frontend interfaces, from automation to AI, I enjoy working across the entire tech landscape—because true innovation often happens at the intersection of multiple fields.",
      "I believe that leadership isn’t just about titles; it’s about creating environments where ideas can grow, risks can be taken, and lessons can be learned without fear of failure.",
      "Resilience and curiosity drive me. Whether it's a new framework, an emerging technology, or an unconventional idea, I’m always ready to dive in, break it down, and build something better.",
      "I value execution over perfection but never compromise on long-term vision. Building products that last requires both speed and thoughtfulness, and I aim to balance both.",
      "If you're someone who believes in innovation, experimentation, and building solutions that matter, I'm always open to connect, collaborate, and explore new possibilities together.",
      "\n",
      "My journey in tech started with curiosity about how things work under the hood",
      "which naturally led me to Arch Linux and the philosophy of understanding",
      "every component of your system.",
      "\n",
      "When I’m not coding or building products, I like to spend my time:",
      "🔧 Reading books and exploring new concepts.",
      "🔧 Playing games to unwind and recharge.",
      "🔧 Researching emerging technologies and innovative ideas.",
      "Customizing my Arch setup",
      "🧪 Experimenting with new technologies"
    ]