export const contact = [
      "Get In Touch:",
      "============",
      "\n",
      "📧 Email: [link: 'mailto:adarshpanditdev@gmail.com']adarshpanditdev@gmail.com",
      "🐙 GitHub: [link: 'https://github.com/DynamicAdi']@DynamicAdi",
      "💼 LinkedIn: [link: 'https://www.linkedin.com/in/devadarsh']@devAdarsh",
      "🐦 Twitter: [link: 'https://twitter.com/modern_coder']@Modern_Coder",
      "🌐 Website: [link: 'https://devadarsh.tech']devadarsh.tech",
      "💬 Instagram: [link: 'https://instagram.com/A.Versatile.Studio']@A.Versatile.Studio",
      "\n",
      "📍 Location: Siliguri, West Bengal, India",
      "🕒 Timezone: GMT+05:30",
      "\n",
      "💡 Always open to interesting projects and collaborations!",
      "Feel free to reach out if you want to build something amazing together.",
    ]