export const experience = [
      "Work Experience:",
      "=================================================================",
      "\n",
      "💼 CTO, CO-FOUNDER | Voltsec.io (2024-PRESENT)",
      "   • Only Developer to built Ai x Nueral Engine for Voltsec.io",
      "   • Voltsec.io is pentest tool which can scan upto 50K+ Vulnerabilities.",
      "   • Voltsec.io provides pentest service for - Web, Network, Apps, Api & Cloud.",
      "   • Visit - https://voltsec.io/",
      "\n",
      "🚀 CTO, CO-FOUNDER | The  RD GROUP OF INDUSTRIES (2024-PRESENT)",
      "   • Responsible for building large client based projects",
      "   • Handle Whole Tech Team for projects",
      "   • Reduced deployment time from hours to minutes with immersive planning",
      "   • Visit - https://therdgroupofindustries.in/",
      "\n",
      "🚀 Head Metatronics Engineer, CO-FOUNDER | Safewings (2025-PRESENT)",
      "   • Built a hardware girls safety 'Protection' Drone in unique sphere shape.",
      "   • Able to pull of complex physical challenges with ease.",
      "   • Revolutionary Product to protect girls from a brutal crime 'R*pe and reduce the crime rates to as minimum as 0.",
      "   • Visit - https://safewing.therdgroupofindustries.in/",
      "\n",
      "🎯 CEO | A Versatile Studio (2025-PRESENT)",
      "   • Advanded Apps Development.",
      "   • 3D CGI, VFX, Games Development",
      "   • Editing, Games Development, 3D, Apps Developement and lots other complex Works are done in Versatile Studio",
      "\n",
      "🔧 Freelance Developer (2020-2021)",
      "   • Built custom solutions for small businesses known as Hobbiest codes.",
      "   • Specialized in e-commerce and CMS development, 3D Render, 3D product selling.",
      "   • Maintained 98% client satisfaction rate and traffic of upto 2K per day from accross the world",
    ]