export const help =  [
      "Available commands:",
      "",
      "  📋 GENERAL:",
      "     about          - Learn about me",
      "     contact        - Let's get in touch",
      "     whoami         - Display current user",
      "\n",
      "  💼 PORTFOLIO:",
      "     skills         - View my technical skills",
      "     projects       - Browse my projects",
      "     projects gallery - Open interactive project gallery",
      "     experience     - View work experience",
      "\n",
      "  🖥️  SYSTEM:",
      "     neofetch       - System information",
      "     ls             - List directory contents",
      "     cd             - Print current directory & Change directory",
      "     clear          - Clear terminal",
      "\n",
      "  🎨 CUSTOMIZATION:",
      "     themes         - List available themes",
      "     theme <name>   - Change terminal theme",
      "     sound toggle   - Toggle sound effects",
      "     ambient toggle - Toggle ambient sounds",
      "\n",
      "  🚀 SPECIAL:",
      // "     sudo gui start - Launch GUI mode",
      "     exit           - Close terminal",
      "",
      "Pro tip: Use Tab for autocomplete and ↑/↓ for command history",
    ]