export const neofetch = [
  "                   -`                    mesterious@imagination",
  "                  .o+`                   ─────────────────────────────",
  "                 `ooo/                   System: Human v2025-LTS",
  "                `+oooo:                  Codename: The Curious One",
  "               `+oooooo:                 Uptime: 21 Years of Debugging Life",
  "               -+oooooo+:                Projects Installed: 137+",
  "             `/:-:++oooo+:               Default Shell: /bin/brain",
  "            `/++++/+++++++:              Display: 2 Eyes @ 1920x1080",
  "           `/++++++++++++++:             Desktop Env: Organized Chaos",
  "          `/+++ooooooooo+++/             Window Mngr: Tabs & Post-its",
  "         ./ooosssso++osssssso+`          Theme: Dark Mode Life™",
  "        .oossssso-````/ossssss+`         Icon Pack: Doodles & Scribbles",
  "       -osssssso.      :ssssssso.        Terminal: Thoughts CLI",
  "      :osssssss/        osssso+++.       Processor: Overthinking v9.0",
  "     /ossssssss/        +ssssooo/-       Graphics: Mental Images RTX™",
  "   `/ossssso+/:-        -:/+osssso+-     Skillset: Versatile",
  "  `+sso+:-`                 `.-/+oso:    RAM: Infinity~GB Art Memories",
  " `++:.                           `-/+/",   
  " .`                                 `/",
]
