export const projects = [
      "Featured Projects:",
      "=================",
      "\n",
      "🚀 Voltsec.io - AI-Powered Vulnerabilities scanner",
      "   • Built with Python, FastAPI, and Next.js, Java, GO.",
      "   • Helps companies to identify and fix bugs in their products.",
      "   • Developers friendly with a focus on security.",
      "\n",
      "🎨 UniRun - Inline code output for multiple languages for VSCode",
      "   • Developed with TypeScript and the only solution of its kind.",
      "   • Enhances coding experience by providing inline code output.",
      "   • Supports more than 10+ programming languages.",
      "\n",
      "🎨 Safewing - Protective Drone for girls safety",
      "   • Only solution to protect girls from a brutal crime Rape.",
      "   • Custom OS and Unique design of hardware build for safety.",
      "   • Build as your own protective bodygaurd with advanced alogrithm to take active only on true crime.",
      "\n",
      
      "This is not enough. View more at: projects gallery",
    ]