export const skills = [
  "🛠️ Technical Skills:",
  "==============================================",
  "\n",

  "🎨 UI/UX Design & 3D Art:",
  "   • UI Design: Figma, Penpot, Adobe XD, Adobe Illustrator, HiPaint",
  "   • UX Research: User flow mapping, A/B testing, Wireframing, Prototyping",
  "   • 3D Modeling: Blender",
  "   • 3D Animation: Rigging, Motion Graphics, Scene Composition",
  "   • Rendering & Texturing: Cycles, Eevee, Substance Painter",
  "\n",

  "💻 Programming Languages:",
  "   • Python",
  "   • TypeScript, JavaScript",
  "   • GO",
  "   • Dart",
  "   • Shell",
  "\n",

  "📦 Frameworks & Libraries:",
  "   • Vite, React, Next.js, Angular",
  "   • Express, FastAPI, Node",
  "   • Tailwind CSS, Styled Components",
  "   • Three.js, WebGL, React-Three-Fiber",
  "   • React-Native, nativewind, Flutter, Expo",
  "\n",

  "🎯 Frontend Development:",
  "   • Modern UI/UX implementation",
  "   • Responsive Web Design",
  "   • Interactive graphics & animations",
  "   • Performance optimization & accessibility best practices",
  "\n",

  "⚙️ Backend Development:",
  "   • Node.js, Python, Go",
  "   • REST API & GraphQL design",
  "   • PostgreSQL, MongoDB, Redis",
  "   • Authentication, Authorization, Security (OAuth, JWT)",
  "   • Scalable API",
  "\n",

  "📱 App Development:",
  "   • React Native, Flutter",
  "   • Progressive Web Apps (PWA)",
  "   • Cross-platform mobile applications",
  "\n",

  "🧰 CLI Development:",
  "   • Node.js (Commander.js, Ink)",
  "   • Python (Typer, Click)",
  "\n",

  "☁️ DevOps & Infrastructure:",
  "   • Docker, Kubernetes, Podman",
  "   • AWS, GCP, Azure",
  "   • CI/CD pipelines (GitHub Actions, GitLab CI, Jenkins)",
  "   • Infrastructure as Code (Terraform, Ansible)",
  "   • Server Management",
  "\n",

  "🤖 AI / ML / Data Science:",
  "   • TensorFlow, PyTorch, Scikit-learn",
  "   • Computer Vision, NLP, Data Analysis (Pandas, NumPy)",
  "   • MLOps and Model Deployment",
  "   • Building AI pipelines and APIs",
  "\n",

  "🎮 Game Development:",
  "   • Unity, Unreal Engine, Godot",
  "   • Web-based Games (Three.js, Canvas, Babylon.js)",
  "   • C#, C++, JavaScript game logic",
  "   • Blender for 3D Graphics",
  "\n",

  "🖥️ System Programming & Low-Level Development:",
  "   • Linux kernel modules & drivers",
  "   • Network programming (Sockets, HTTP/2, WebSockets)",
  "   • Shell scripting, Process management",
  "   • Performance tuning & system architecture",
  "\n",

  "🧑‍💼 Product & Team Skills:",
  "   • Team building & technical mentorship",
  "   • Product strategy & roadmap execution",
  "   • Agile methodologies (Scrum, Kanban)",
  "   • Cross-functional collaboration with design & marketing teams",
  "   • Go-to-Market strategy alignment with tech execution",
  "\n",

  "🔐 Cybersecurity:",
  "   • Secure coding practices (OWASP Top 10)",
  "   • API Security, Authentication/Authorization best practices",
  "   • SSL/TLS, JWT, OAuth2 implementations",
  "   • Penetration testing basics & vulnerability assessment",
  "   • Co Founder and creator of Voltsec.io (Penetration testing tool)",
  "\n",

  "🧪 Testing & QA Automation:",
  "   • Unit & Integration Testing (Jest, Mocha, PyTest)",
  "   • End-to-End Testing (Cypress, Playwright)",
  "   • Load & Performance Testing (k6, JMeter)",
  "   • Automated CI/CD Testing Pipelines",
]